version: "3"

services:
    6mkt-api:
        image: 6mkt/123vendido:latest
        build:
            context: ../src
            dockerfile: ./backend/microservices/backoffice/6MKT.BackOffice.Api/Dockerfile
        ports:
            - 5001:5001
        environment:
            - ASPNETCORE_URLS=http://*:5001