version: "3"

services:
    6mkt-sso:
        image: 6mkt/sso:latest
        container_name: sso-api-6mkt
        build:
            context: ../src
            dockerfile: ./backend/microservices/sso/6MKT.Identity.Api/Dockerfile
        ports:
            - 5002:5002
        environment:
            - ASPNETCORE_URLS=http://*:5002
    6mkt-api:
        image: 6mkt/123vendido:latest
        container_name: vendido-api
        build:
            context: ../src
            dockerfile: ./backend/microservices/backoffice/6MKT.BackOffice.Api/Dockerfile
        ports:
            - 5001:5001
        environment:
            - ASPNETCORE_URLS=http://*:5001
        depends_on:
           - 6mkt-sso  